"""
pipeline/shadow_classifier.py — Task 8 Stance-Aware Shadow Jab-Cross Classifier MVP

Module implementing shadow classification for straight punches (jab/cross)
using stance context and action-window kinematic features.

Key Design Principles:
1. Shadow Mode Isolation:
   - Does NOT mutate existing legacy detector outputs or ActionResult public properties.
   - Outputs ClassificationDecision serializable to dict matching Zod shadowClassificationSchema.
2. Canonical Data Contracts:
   - Canonical EvidenceLevel imported from pipeline.contracts
   - DecisionStatus (CLASSIFIED, ABSTAINED, REJECTED_CANDIDATE)
   - TechniqueCandidate (technique, family, attacking_side, limb_role, stance)
   - ClassifierProvenance (classifier_id, classifier_version, config_version, feature_version, stance_source)
   - ShadowClassifierConfig (thresholds for elbow extension, directness, curvature, reach)
   - ClassificationDecision (to_dict parity with frontend schema)
3. Guardrails:
   - Case A: Missing or unsupported evidence -> ABSTAINED, evidenceLevel="unavailable", reasonCodes=["INSUFFICIENT_EVIDENCE"].
   - Case B: Unresolved stance/limb -> ABSTAINED, evidenceLevel="derived_proxy", reasonCodes=["UNRESOLVED_STANCE_OR_LIMB"].
   - Case C: Curved punch / low extension -> REJECTED_CANDIDATE, reasonCodes=["CURVED_TRAJECTORY_REJECTED"] / ["INSUFFICIENT_EXTENSION_OR_REACH"].
   - Case D: Nominal straight punch -> CLASSIFIED, lead=jab, rear=cross, confidence=None, evidenceLevel="derived_proxy".
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum
import math
from typing import Any, Optional, Union

from pipeline.contracts import EvidenceLevel
from pipeline.stance_context import (
    StanceContext,
    StanceType,
    normalize_attacking_side,
    resolve_limb_role,
)

__all__ = [
    "EvidenceLevel",
    "DecisionStatus",
    "TechniqueCandidate",
    "ClassifierProvenance",
    "ShadowClassifierConfig",
    "ClassificationDecision",
    "ShadowClassifier",
    "classify_shadow_punch",
]


# ===========================================================================
# Canonical Enums & Data Contracts
# ===========================================================================

class DecisionStatus(str, Enum):
    CLASSIFIED = "classified"
    ABSTAINED = "abstained"
    REJECTED_CANDIDATE = "rejected_candidate"


@dataclass(frozen=True)
class TechniqueCandidate:
    """Candidate prediction generated by the shadow classifier."""
    technique: str        # e.g. "jab", "cross"
    family: str = "punch" # "punch" | "kick" | "other_strike" | "non_strike"
    attacking_side: str = "unknown"   # "left" | "right" | "unknown"
    limb_role: str = "unknown"        # "lead" | "rear" | "unknown"
    stance: str = "unknown"           # "orthodox" | "southpaw" | "switch" | "unknown"


@dataclass(frozen=True)
class ClassifierProvenance:
    """Provenance tracking classifier ID, version, config, and stance source."""
    classifier_id: str = "shadow_jab_cross_classifier"
    classifier_version: str = "1.0.0"
    config_version: str = "1.0.0"
    feature_version: str = "1.0.0"
    stance_source: str = "stance_context"


@dataclass(frozen=True)
class ShadowClassifierConfig:
    """Configurable thresholds for geometric & kinematic straight punch gating."""
    config_version: str = "1.0.0"
    min_elbow_extension_deg: float = 140.0
    min_trajectory_directness: float = 0.82
    max_tangential_curvature: float = 0.20
    min_reach_ratio: float = 0.70


@dataclass(frozen=True)
class ClassificationDecision:
    """
    Result of shadow classification with field-for-field parity to
    frontend Zod shadowClassificationSchema.
    """
    status: DecisionStatus
    candidate: Optional[TechniqueCandidate]
    reason_codes: tuple[str, ...]
    provenance: ClassifierProvenance
    confidence: Optional[float] = None
    evidence_level: EvidenceLevel = EvidenceLevel.DERIVED_PROXY

    def to_dict(self) -> dict[str, Any]:
        """Convert decision to dict matching frontend shadowClassificationSchema."""
        return {
            "status": self.status.value,
            "candidate": {
                "technique": self.candidate.technique,
                "family": self.candidate.family,
                "attackingSide": self.candidate.attacking_side,
                "limbRole": self.candidate.limb_role,
                "stance": self.candidate.stance,
            } if self.candidate is not None else None,
            "confidence": self.confidence,
            "reasonCodes": list(self.reason_codes),
            "classifierId": self.provenance.classifier_id,
            "classifierVersion": self.provenance.classifier_version,
            "configVersion": self.provenance.config_version,
            "featureVersion": self.provenance.feature_version,
            "stanceSource": self.provenance.stance_source,
            "evidenceLevel": self.evidence_level.value,
        }


# ===========================================================================
# Helper: Feature Extraction & Input Validation
# ===========================================================================

RECOGNIZED_FEATURE_ATTRS = {
    "metrics",
    "arm",
    "arm_side",
    "attacking_side",
    "elbow_extension_deg",
    "elbow_extension_angle",
    "max_elbow_angle",
    "trajectory_directness",
    "directness",
    "tangential_curvature",
    "max_tangential_curvature",
    "curvature",
    "reach_ratio",
    "reach",
    "is_evidence_missing",
}


def _unwrap_value(val: Any) -> Optional[float]:
    """Helper to unwrap numeric value from float, int, or KinematicMetricContract."""
    if val is None or isinstance(val, bool):
        return None
    try:
        if hasattr(val, "value"):
            val = val.value
        if val is None or isinstance(val, bool):
            return None
        fval = float(val)
        if math.isnan(fval) or math.isinf(fval):
            return None
        return fval
    except (TypeError, ValueError, AttributeError):
        return None


def _extract_punch_features(
    features: Any,
) -> tuple[Optional[str], Optional[float], Optional[float], Optional[float], Optional[float], bool]:
    """
    Extract (arm, elbow_extension_deg, trajectory_directness, tangential_curvature, reach_ratio, is_missing)
    from duck-typed inputs (dict, KinematicFeatureSet, PunchDerivedFeatures, etc.).
    Returns (None, None, None, None, None, True) if features is unsupported or missing.
    """
    if features is None:
        return None, None, None, None, None, True

    # Primitive types (int, float, str, list, set, tuple, bool, bytes) are unsupported feature objects
    if isinstance(features, (int, float, str, list, set, tuple, bool, bytes)):
        return None, None, None, None, None, True

    # 1. FeatureSet with Mapping metrics (e.g. KinematicFeatureSet / MappingProxyType)
    if hasattr(features, "metrics"):
        try:
            metrics = getattr(features, "metrics", None)
            if isinstance(metrics, Mapping):
                arm = getattr(features, "arm", getattr(features, "arm_side", getattr(features, "attacking_side", None)))
                elbow_metric = metrics.get("elbow_extension_angle") or metrics.get("elbow_extension_deg")
                direct_metric = metrics.get("trajectory_directness")
                curv_metric = metrics.get("max_tangential_curvature") or metrics.get("tangential_curvature")
                reach_metric = metrics.get("reach_ratio")
                return (
                    str(arm) if arm is not None else None,
                    _unwrap_value(elbow_metric),
                    _unwrap_value(direct_metric),
                    _unwrap_value(curv_metric),
                    _unwrap_value(reach_metric),
                    False,
                )
        except Exception:
            return None, None, None, None, None, True

    # 2. Dictionary / Mapping input
    if isinstance(features, Mapping):
        arm = features.get("arm") or features.get("arm_side") or features.get("attacking_side")
        elbow = features.get("elbow_extension_deg") or features.get("elbow_extension_angle") or features.get("max_elbow_angle")
        direct = features.get("trajectory_directness") or features.get("directness")
        curv = features.get("tangential_curvature") or features.get("max_tangential_curvature") or features.get("curvature")
        reach = features.get("reach_ratio") or features.get("reach")
        missing = bool(features.get("is_evidence_missing", False))
        return (
            str(arm) if arm is not None else None,
            _unwrap_value(elbow),
            _unwrap_value(direct),
            _unwrap_value(curv),
            _unwrap_value(reach),
            missing,
        )

    # 3. Object / Dataclass input: must have at least one recognized feature attribute
    has_recognized_attr = any(hasattr(features, attr) for attr in RECOGNIZED_FEATURE_ATTRS)
    if not has_recognized_attr:
        return None, None, None, None, None, True

    try:
        arm = getattr(features, "arm", getattr(features, "arm_side", getattr(features, "attacking_side", None)))
        elbow = getattr(features, "elbow_extension_deg", getattr(features, "elbow_extension_angle", getattr(features, "max_elbow_angle", None)))
        direct = getattr(features, "trajectory_directness", getattr(features, "directness", None))
        curv = getattr(features, "tangential_curvature", getattr(features, "max_tangential_curvature", getattr(features, "curvature", None)))
        reach = getattr(features, "reach_ratio", getattr(features, "reach", None))
        missing = bool(getattr(features, "is_evidence_missing", False))

        return (
            str(arm) if arm is not None else None,
            _unwrap_value(elbow),
            _unwrap_value(direct),
            _unwrap_value(curv),
            _unwrap_value(reach),
            missing,
        )
    except Exception:
        return None, None, None, None, None, True


# ===========================================================================
# Shadow Classifier Engine
# ===========================================================================

class ShadowClassifier:
    """
    Pure stateless stance-aware straight punch classifier.
    Runs in shadow mode, outputting ClassificationDecision.
    """

    def __init__(self, config: Optional[ShadowClassifierConfig] = None) -> None:
        self.config = config or ShadowClassifierConfig()

    def classify(
        self,
        features: Any,
        stance_context: Optional[StanceContext],
        provenance: Optional[ClassifierProvenance] = None,
    ) -> ClassificationDecision:
        """
        Classify a punch candidate into jab, cross, abstained, or rejected.

        :param features: Derived punch kinematic features (duck-typed).
        :param stance_context: Video-level StanceContext.
        :param provenance: Optional custom provenance overrides.
        :return: ClassificationDecision.
        """
        if stance_context is None:
            stance_source = "unknown"
        else:
            raw_source = getattr(stance_context, "source", "unknown")
            stance_source = raw_source.value if hasattr(raw_source, "value") else str(raw_source)

        prov = provenance or ClassifierProvenance(
            classifier_id="shadow_jab_cross_classifier",
            config_version=self.config.config_version,
            stance_source=stance_source,
        )

        # 1. Guardrail Case A: Missing or Unsupported Evidence
        if features is None:
            return ClassificationDecision(
                status=DecisionStatus.ABSTAINED,
                candidate=None,
                reason_codes=("INSUFFICIENT_EVIDENCE",),
                provenance=prov,
                confidence=None,
                evidence_level=EvidenceLevel.UNAVAILABLE,
            )

        try:
            arm, elbow_ext, directness, curvature, reach, is_missing = _extract_punch_features(features)
        except Exception:
            return ClassificationDecision(
                status=DecisionStatus.ABSTAINED,
                candidate=None,
                reason_codes=("INSUFFICIENT_EVIDENCE",),
                provenance=prov,
                confidence=None,
                evidence_level=EvidenceLevel.UNAVAILABLE,
            )

        if is_missing or (elbow_ext is None and directness is None and curvature is None and reach is None):
            return ClassificationDecision(
                status=DecisionStatus.ABSTAINED,
                candidate=None,
                reason_codes=("INSUFFICIENT_EVIDENCE",),
                provenance=prov,
                confidence=None,
                evidence_level=EvidenceLevel.UNAVAILABLE,
            )

        # 2. Guardrail Case C: Curved Trajectory & Low Extension/Reach Rejections
        rejection_reasons: list[str] = []

        is_curved = False
        if directness is not None and directness < self.config.min_trajectory_directness:
            is_curved = True
        if curvature is not None and curvature > self.config.max_tangential_curvature:
            is_curved = True
        if is_curved:
            rejection_reasons.append("CURVED_TRAJECTORY_REJECTED")

        is_low_extension = False
        if elbow_ext is not None and elbow_ext < self.config.min_elbow_extension_deg:
            is_low_extension = True
        if reach is not None and reach < self.config.min_reach_ratio:
            is_low_extension = True
        if is_low_extension:
            rejection_reasons.append("INSUFFICIENT_EXTENSION_OR_REACH")

        if rejection_reasons:
            return ClassificationDecision(
                status=DecisionStatus.REJECTED_CANDIDATE,
                candidate=None,
                reason_codes=tuple(rejection_reasons),
                provenance=prov,
                confidence=None,
                evidence_level=EvidenceLevel.DERIVED_PROXY,
            )

        # 3. Guardrail Case B: Stance / Limb Resolution Check
        normalized_arm = normalize_attacking_side(arm)
        if stance_context is None:
            resolved_stance = StanceType.UNKNOWN.value
        else:
            raw_stance = getattr(stance_context, "resolved_stance", getattr(stance_context, "stance", StanceType.UNKNOWN.value))
            resolved_stance = raw_stance.value if hasattr(raw_stance, "value") else str(raw_stance)

        limb_role = resolve_limb_role(normalized_arm, resolved_stance)

        if (
            normalized_arm == "unknown"
            or resolved_stance in (StanceType.SWITCH.value, StanceType.UNKNOWN.value)
            or limb_role == "unknown"
        ):
            return ClassificationDecision(
                status=DecisionStatus.ABSTAINED,
                candidate=None,
                reason_codes=("UNRESOLVED_STANCE_OR_LIMB",),
                provenance=prov,
                confidence=None,
                evidence_level=EvidenceLevel.DERIVED_PROXY,
            )

        # 4. Guardrail Case D: Nominal Straight Punch Classification
        if limb_role == "lead":
            technique = "jab"
        elif limb_role == "rear":
            technique = "cross"
        else:
            technique = "unknown_punch"

        candidate = TechniqueCandidate(
            technique=technique,
            family="punch",
            attacking_side=normalized_arm,
            limb_role=limb_role,
            stance=resolved_stance,
        )

        return ClassificationDecision(
            status=DecisionStatus.CLASSIFIED,
            candidate=candidate,
            reason_codes=(),
            provenance=prov,
            confidence=None,
            evidence_level=EvidenceLevel.DERIVED_PROXY,
        )


def classify_shadow_punch(
    features: Any,
    stance_context: Optional[StanceContext],
    config: Optional[ShadowClassifierConfig] = None,
    provenance: Optional[ClassifierProvenance] = None,
) -> ClassificationDecision:
    """Convenience function to classify punch using ShadowClassifier."""
    classifier = ShadowClassifier(config=config)
    return classifier.classify(features, stance_context, provenance=provenance)
